import type { PresentationPreset } from "./presentation-preset-registry";

export const pcProcurementPreset: PresentationPreset = {
  code: "pc_procurement",
  expressions: [
    {
      id: "exp-pc-overview",
      name: "电脑采购总览",
      viewIds: ["view-pc-grid", "view-pc-bi"],
      defaultViewId: "view-pc-grid",
      defaultForm: "grid",
      activityMember: "wangyun",
      lastActivity: "采购事实由工作空间加载",
    },
    {
      id: "exp-pc-plan-map",
      name: "装机方案关系图",
      viewIds: ["view-pc-canvas"],
      defaultViewId: "view-pc-canvas",
      defaultForm: "canvas",
      activityMember: "lixiao",
      lastActivity: "按业务编码绑定方案",
    },
    {
      id: "exp-pc-compare",
      name: "装机方案对比",
      viewIds: ["view-pc-matrix", "view-pc-ana"],
      defaultViewId: "view-pc-matrix",
      defaultForm: "matrix",
      activityMember: "chenmo",
      lastActivity: "比较预算、兼容性与功耗",
    },
    {
      id: "exp-pc-document",
      name: "采购方案说明书",
      viewIds: ["view-pc-doc"],
      defaultViewId: "view-pc-doc",
      defaultForm: "doc",
      activityMember: "wangyun",
      lastActivity: "文档引用随工作空间同步",
    },
  ],
  views: [
    {
      id: "view-pc-grid",
      exprId: "exp-pc-overview",
      kind: "grid",
      config: {
        sourceFallback: true,
        objectTypeCode: "build_plan",
        columns: [
          "code",
          "name",
          "status",
          "total_price_cny_fx",
          "total_power_w_fx",
          "total_performance_score_fx",
        ],
      },
    },
    {
      id: "view-pc-bi",
      exprId: "exp-pc-overview",
      kind: "bi",
      config: {
        layout: "procurement-summary",
        title: "采购指标",
        sourceLabel: "当前电脑采购工作空间",
        emptyLabel: "暂无可展示图表数据",
        objectTypeCodes: ["build_plan", "procurement_requirement"],
      },
    },
    {
      id: "view-pc-canvas",
      exprId: "exp-pc-plan-map",
      kind: "canvas",
      config: {
        nodes: [
          {
            objectId: "pc-ref-requirement",
            x: 380,
            y: 64,
            shownFields: ["code", "name", "budget_cny"],
          },
          {
            objectId: "pc-ref-valid-plan",
            x: 120,
            y: 280,
            shownFields: ["code", "name", "status"],
          },
          {
            objectId: "pc-ref-invalid-plan",
            x: 640,
            y: 280,
            shownFields: ["code", "name", "status"],
          },
        ],
        edges: [
          { relationId: "pc-rel-valid-satisfies" },
          { relationId: "pc-rel-invalid-satisfies" },
        ],
      },
    },
    {
      id: "view-pc-matrix",
      exprId: "exp-pc-compare",
      kind: "matrix",
      config: {
        sourceTypeCode: "build_plan",
        rowField: "status",
        colField: "code",
        cardFields: [
          "total_price_cny_fx",
          "total_power_w_fx",
          "total_performance_score_fx",
        ],
        summary: "count",
        interactionHint: "矩阵直接读取工作空间字段，不在前端重新计算派生值。",
      },
    },
    {
      id: "view-pc-ana",
      exprId: "exp-pc-compare",
      kind: "ana",
      config: {
        reportId: "ana-pc-plan-comparison",
        allowReanalysis: false,
        dashboardExprId: "exp-pc-overview",
      },
    },
    {
      id: "view-pc-doc",
      exprId: "exp-pc-document",
      kind: "doc",
      config: { template: "电脑采购方案说明书" },
    },
  ],
  docModels: [
    {
      exprId: "exp-pc-document",
      docNo: "PC-PROCUREMENT-PLAN",
      template: "电脑采购方案说明书",
      binding: { objectId: "pc-ref-valid-plan" },
      authorLine: "采购工作台 · 数据来自当前工作空间",
      blocks: [
        {
          kind: "meta",
          items: ["电脑采购", "模板:采购方案说明书", "绑定:装机方案"],
        },
        {
          kind: "h1",
          text: "采购方案 · {{ref}}",
          refId: "ref-pc-plan-name",
        },
        { kind: "h2", text: "一、方案概况" },
        {
          kind: "paragraph",
          id: "pc-plan-summary",
          inlines: [
            { kind: "text", text: "方案编码 " },
            { kind: "ref", refId: "ref-pc-plan-code" },
            { kind: "text", text: "，当前生命周期状态为 " },
            { kind: "ref", refId: "ref-pc-plan-status" },
            { kind: "text", text: "。" },
          ],
        },
        { kind: "h2", text: "二、成本与性能" },
        {
          kind: "dataTable",
          id: "pc-plan-metrics",
          title: "方案指标",
          sourceLabel: "装机方案",
          rows: [
            { label: "方案总价", refId: "ref-pc-plan-price" },
            { label: "方案总功耗", refId: "ref-pc-plan-power" },
            { label: "方案性能分", refId: "ref-pc-plan-performance" },
          ],
        },
      ],
    },
  ],
  fieldRefs: [
    {
      id: "ref-pc-plan-name",
      objectId: "pc-ref-valid-plan",
      fieldCode: "name",
      exprId: "exp-pc-document",
      label: "方案名称",
      state: "fresh",
    },
    {
      id: "ref-pc-plan-code",
      objectId: "pc-ref-valid-plan",
      fieldCode: "code",
      exprId: "exp-pc-document",
      label: "方案编码",
      state: "fresh",
    },
    {
      id: "ref-pc-plan-status",
      objectId: "pc-ref-valid-plan",
      fieldCode: "status",
      exprId: "exp-pc-document",
      label: "生命周期状态",
      state: "fresh",
    },
    {
      id: "ref-pc-plan-price",
      objectId: "pc-ref-valid-plan",
      fieldCode: "total_price_cny_fx",
      exprId: "exp-pc-document",
      label: "方案总价",
      state: "fresh",
    },
    {
      id: "ref-pc-plan-power",
      objectId: "pc-ref-valid-plan",
      fieldCode: "total_power_w_fx",
      exprId: "exp-pc-document",
      label: "方案总功耗",
      state: "fresh",
    },
    {
      id: "ref-pc-plan-performance",
      objectId: "pc-ref-valid-plan",
      fieldCode: "total_performance_score_fx",
      exprId: "exp-pc-document",
      label: "方案性能分",
      state: "fresh",
    },
  ],
  kpis: [
    {
      id: "kpi-pc-budget",
      label: "需求预算",
      value: "—",
      delta: "工作空间派生",
      deltaSign: "flat",
      sourceLabel: "采购需求",
      visible: true,
    },
    {
      id: "kpi-pc-price",
      label: "方案总价",
      value: "—",
      delta: "供应商报价口径",
      deltaSign: "flat",
      sourceLabel: "装机方案",
      visible: true,
    },
    {
      id: "kpi-pc-power",
      label: "方案总功耗",
      value: "—",
      delta: "含 20% 电源余量校验",
      deltaSign: "flat",
      sourceLabel: "装机方案",
      visible: true,
    },
    {
      id: "kpi-pc-performance",
      label: "方案性能分",
      value: "—",
      delta: "配件性能汇总",
      deltaSign: "flat",
      sourceLabel: "装机方案",
      visible: true,
    },
  ],
  biBars: [],
  anaReports: [
    {
      id: "ana-pc-plan-comparison",
      viewId: "view-pc-ana",
      scopeLabel: "当前电脑采购工作空间",
      question: "方案在预算、兼容性、功耗与性能上有何差异？",
      sourcesLabel: "采购需求 + 装机方案 + 供应商报价",
      factorTitle: "方案因素",
      factorMetricLabel: "当前预设未提供分析算法",
      factors: [],
      drillTitle: "方案明细",
      drillTraceLabel: "数据来自当前工作空间",
      drillColumns: [],
      drillRows: [],
      insights: [
        {
          title: "规则口径",
          segments: [
            { text: "有效性由规则结果决定，生命周期状态不表示校验结论。" },
          ],
        },
      ],
      pinKpiId: "kpi-pc-price",
      childKpiIds: ["kpi-pc-power", "kpi-pc-performance"],
      childActionLabel: "生成指标子看板",
    },
  ],
  slotBindings: [],
  objectBindings: [
    {
      presentationId: "pc-ref-requirement",
      objectTypeCode: "procurement_requirement",
      fields: { code: "REQ-PC-001" },
    },
    {
      presentationId: "pc-ref-valid-plan",
      objectTypeCode: "build_plan",
      fields: { code: "PLAN-PC-VALID", name: "兼容工作站方案" },
    },
    {
      presentationId: "pc-ref-invalid-plan",
      objectTypeCode: "build_plan",
      fields: { code: "PLAN-PC-INVALID", name: "超预算不兼容方案" },
    },
  ],
  relationBindings: [
    {
      presentationId: "pc-rel-valid-satisfies",
      relationTypeCode: "build_plan_satisfies_requirement",
      sourceId: "pc-ref-valid-plan",
      targetId: "pc-ref-requirement",
    },
    {
      presentationId: "pc-rel-invalid-satisfies",
      relationTypeCode: "build_plan_satisfies_requirement",
      sourceId: "pc-ref-invalid-plan",
      targetId: "pc-ref-requirement",
    },
  ],
};
