import type { PresentationPreset } from "./presentation-preset-registry";

export const pcProcurementPreset: PresentationPreset = {
  code: "pc_procurement",
  expressions: [
    {
      id: "exp-pc-overview",
      name: "电脑采购总览",
      viewIds: ["view-pc-grid", "view-pc-bi"],
      defaultViewId: "view-pc-grid",
      defaultForm: "grid",
      activityMember: "wangyun",
      lastActivity: "采购事实由工作空间加载",
    },
    {
      id: "exp-pc-plan-map",
      name: "装机方案关系图",
      viewIds: ["view-pc-canvas"],
      defaultViewId: "view-pc-canvas",
      defaultForm: "canvas",
      activityMember: "lixiao",
      lastActivity: "按业务编码绑定方案",
    },
    {
      id: "exp-pc-compare",
      name: "装机方案对比",
      viewIds: ["view-pc-matrix", "view-pc-ana"],
      defaultViewId: "view-pc-matrix",
      defaultForm: "matrix",
      activityMember: "chenmo",
      lastActivity: "比较预算、兼容性与功耗",
    },
    {
      id: "exp-pc-document",
      name: "采购方案说明书",
      viewIds: ["view-pc-doc"],
      defaultViewId: "view-pc-doc",
      defaultForm: "doc",
      activityMember: "wangyun",
      lastActivity: "文档引用随工作空间同步",
    },
  ],
  views: [
    {
      id: "view-pc-grid",
      exprId: "exp-pc-overview",
      kind: "grid",
      config: {
        objectTypeCode: "build_plan",
        columns: [
          "code",
          "name",
          "status",
          { fieldCode: "total_price_cny_fx", unit: "CNY" },
          { fieldCode: "total_power_w_fx", unit: "W" },
          "total_performance_score_fx",
        ],
        defaultSort: { fieldCode: "code", direction: "asc" },
        filterFields: ["status", "name"],
        pageSize: 20,
        title: "电脑采购方案清单",
        description: "方案数据与派生指标来自当前工作空间。",
        emptyLabel: "当前工作空间暂无采购方案。",
        validation: {
          enabled: true,
          objectTypeCode: "build_plan",
          position: "bottom",
          allowManualRun: true,
        },
      },
    },
    {
      id: "view-pc-bi",
      exprId: "exp-pc-overview",
      kind: "bi",
      config: {
        layout: "procurement-summary",
        title: "采购指标",
        sourceLabel: "当前电脑采购工作空间",
        emptyLabel: "暂无可展示图表数据",
        objectTypeCodes: ["build_plan", "procurement_requirement"],
        metrics: [
          {
            id: "pc-build-plan-count",
            kind: "count",
            label: "方案数量",
            objectTypeCode: "build_plan",
            sourceLabel: "装机方案",
          },
        ],
        recordSeries: {
          objectTypeCode: "build_plan",
          labelFieldCode: "name",
          valueFieldCode: "total_price_cny_fx",
        },
      },
    },
    {
      id: "view-pc-canvas",
      exprId: "exp-pc-plan-map",
      kind: "canvas",
      config: {
        selectionObjectTypeCode: "build_plan",
        selectionRelationTypeCodes: [
          "build_plan_satisfies_requirement",
          "build_plan_contains_item",
          "build_plan_item_selects_product",
          "build_plan_item_uses_supplier_quote",
          "supplier_quote_for_product",
          "supplier_quote_offered_by_supplier",
        ],
        selectionDepth: 3,
        nodes: [
          {
            objectId: "pc-ref-requirement",
            x: 380,
            y: 64,
            shownFields: ["code", "name", "total_budget_cny_fx"],
          },
          {
            objectId: "pc-ref-valid-plan",
            x: 120,
            y: 280,
            shownFields: ["code", "name", "status"],
          },
          {
            objectId: "pc-ref-invalid-plan",
            x: 640,
            y: 280,
            shownFields: ["code", "name", "status"],
          },
          {
            objectId: "pc-ref-valid-cpu-item",
            x: 80,
            y: 496,
            shownFields: ["code", "name", "quantity"],
          },
          {
            objectId: "pc-ref-valid-cpu-product",
            x: 324,
            y: 496,
            shownFields: ["code", "name", "category"],
          },
          {
            objectId: "pc-ref-valid-cpu-quote",
            x: 568,
            y: 496,
            shownFields: ["code", "name", "unit_price_cny"],
          },
        ],
        edges: [
          { relationId: "pc-rel-valid-satisfies" },
          { relationId: "pc-rel-invalid-satisfies" },
          { relationId: "pc-rel-valid-contains-cpu" },
          { relationId: "pc-rel-valid-cpu-selects-product" },
          { relationId: "pc-rel-valid-cpu-uses-quote" },
          { relationId: "pc-rel-valid-cpu-quote-for-product" },
        ],
      },
    },
    {
      id: "view-pc-matrix",
      exprId: "exp-pc-compare",
      kind: "matrix",
      config: {
        sourceTypeCode: "build_plan",
        rowField: "status",
        colField: "code",
        cardFields: [
          "total_price_cny_fx",
          "requirement_budget_cny_fx",
          "total_power_w_fx",
          "total_performance_score_fx",
          "power_supply_capacity_w_fx",
          "cpu_mainboard_platform_span_fx",
          "memory_platform_span_fx",
        ],
        summary: "count",
        interactionHint: "矩阵直接读取工作空间字段，不在前端重新计算派生值。",
      },
    },
    {
      id: "view-pc-ana",
      exprId: "exp-pc-compare",
      kind: "ana",
      config: {
        reportId: "ana-pc-plan-comparison",
        allowReanalysis: false,
        dashboardExprId: "exp-pc-overview",
      },
    },
    {
      id: "view-pc-doc",
      exprId: "exp-pc-document",
      kind: "doc",
      config: {
        template: "电脑采购方案说明书",
        structuredDocument: {
          bodyFieldCode: "body",
          dataReferenceTemplates: [
            {
              id: "plan-name",
              label: "方案名称",
              config: {
                objectBinding: "document-root",
                objectTypeCode: "build_plan",
                fieldCode: "name",
              },
            },
          ],
          dataTableTemplates: [
            {
              id: "plan-items",
              label: "方案明细表",
              config: {
                scope: "document-root",
                objectTypeCode: "build_plan_item",
                relationTypeCode: "build_plan_contains_item",
                maxRows: 50,
                sort: { fieldCode: "code", direction: "asc" },
                allowRowSelection: true,
                showDerivedBadge: true,
                columns: [
                  { id: "code", label: "明细编码", fieldCode: "code" },
                  { id: "name", label: "明细名称", fieldCode: "name" },
                  { id: "quantity", label: "数量", fieldCode: "quantity" },
                  {
                    id: "product",
                    label: "硬件配件",
                    fieldCode: "name",
                    relationPath: ["build_plan_item_selects_product"],
                  },
                  {
                    id: "quote",
                    label: "供应商报价",
                    fieldCode: "name",
                    relationPath: ["build_plan_item_uses_supplier_quote"],
                  },
                  {
                    id: "supplier",
                    label: "供应商",
                    fieldCode: "name",
                    relationPath: [
                      "build_plan_item_uses_supplier_quote",
                      "supplier_quote_offered_by_supplier",
                    ],
                  },
                  {
                    id: "price",
                    label: "单价",
                    fieldCode: "selected_unit_price_cny_fx",
                  },
                  {
                    id: "total",
                    label: "明细总价",
                    fieldCode: "total_price_cny_fx",
                  },
                  { id: "power", label: "明细功耗", fieldCode: "power_w_fx" },
                  {
                    id: "performance",
                    label: "性能分",
                    fieldCode: "selected_performance_score_fx",
                  },
                  {
                    id: "inventory",
                    label: "库存",
                    fieldCode: "quote_inventory_fx",
                  },
                ],
              },
            },
          ],
          output: {
            format: "docx",
            relationType: "build_plan_contains_item",
            maxDepth: 1,
            relatedRelationTypes: [
              "build_plan_satisfies_requirement",
              "build_plan_contains_item",
              "build_plan_item_selects_product",
              "build_plan_item_uses_supplier_quote",
              "supplier_quote_for_product",
              "supplier_quote_offered_by_supplier",
            ],
            fieldOrder: [
              "code",
              "name",
              "status",
              "total_price_cny_fx",
              "total_power_w_fx",
              "total_performance_score_fx",
              "power_supply_capacity_w_fx",
            ],
            sectionMapping: {
              fieldRoles: {
                code: "table",
                name: "table",
                status: "table",
                total_price_cny_fx: "table",
                total_power_w_fx: "table",
                total_performance_score_fx: "table",
                power_supply_capacity_w_fx: "table",
              },
              fieldLabels: {
                code: "编码",
                name: "名称",
                status: "状态",
                total_price_cny_fx: "方案总价（元）",
                total_power_w_fx: "方案总功耗（瓦）",
                total_performance_score_fx: "方案性能分",
                power_supply_capacity_w_fx: "电源容量（瓦）",
              },
              relationTables: [
                {
                  relationType: "build_plan_satisfies_requirement",
                  title: "采购需求摘要",
                  columns: [
                    { label: "需求编码", fieldCode: "code" },
                    { label: "需求名称", fieldCode: "name" },
                    { label: "岗位", fieldCode: "job_role" },
                    { label: "采购数量", fieldCode: "quantity" },
                    { label: "单台预算（元）", fieldCode: "unit_budget_cny" },
                    { label: "总预算（元）", fieldCode: "total_budget_cny_fx" },
                    { label: "保修要求", fieldCode: "warranty_requirement" },
                    { label: "系统要求", fieldCode: "os_requirement" },
                    {
                      label: "整机最大设计功耗（瓦）",
                      fieldCode: "max_total_power_w",
                    },
                  ],
                },
                {
                  relationType: "build_plan_contains_item",
                  title: "方案明细表",
                  columns: [
                    { label: "明细编码", fieldCode: "code" },
                    { label: "明细名称", fieldCode: "name" },
                    { label: "数量", fieldCode: "quantity" },
                    {
                      label: "产品编码",
                      fieldCode: "code",
                      relationPath: ["build_plan_item_selects_product"],
                    },
                    {
                      label: "产品名称",
                      fieldCode: "name",
                      relationPath: ["build_plan_item_selects_product"],
                    },
                    {
                      label: "报价编码",
                      fieldCode: "code",
                      relationPath: ["build_plan_item_uses_supplier_quote"],
                    },
                    {
                      label: "供应商",
                      fieldCode: "name",
                      relationPath: [
                        "build_plan_item_uses_supplier_quote",
                        "supplier_quote_offered_by_supplier",
                      ],
                    },
                    {
                      label: "单价（元）",
                      fieldCode: "selected_unit_price_cny_fx",
                    },
                    {
                      label: "明细总价（元）",
                      fieldCode: "total_price_cny_fx",
                    },
                    { label: "功耗（瓦）", fieldCode: "power_w_fx" },
                    {
                      label: "性能分",
                      fieldCode: "selected_performance_score_fx",
                    },
                    { label: "报价库存", fieldCode: "quote_inventory_fx" },
                  ],
                },
              ],
            },
          },
          preferSelectedRoot: true,
          root: {
            objectTypeCode: "build_plan",
            fields: [
              "code",
              "name",
              "status",
              "total_price_cny_fx",
              "total_power_w_fx",
              "total_performance_score_fx",
            ],
            editableFields: ["name", "status"],
          },
          sections: [
            {
              relationTypeCode: "build_plan_contains_item",
              title: "方案明细",
              createAction: "pc_procurement.procurement-item",
              objectTypeCode: "build_plan_item",
              fields: [
                "code",
                "name",
                "quantity",
                "selected_unit_price_cny_fx",
                "total_price_cny_fx",
                "power_w_fx",
                "selected_performance_score_fx",
              ],
              editableFields: ["name", "quantity"],
            },
            {
              relationTypeCode: "build_plan_satisfies_requirement",
              title: "采购需求",
              objectTypeCode: "procurement_requirement",
              fields: [
                "code",
                "name",
                "job_role",
                "quantity",
                "unit_budget_cny",
                "total_budget_cny_fx",
                "warranty_requirement",
                "os_requirement",
                "max_total_power_w",
              ],
              editableFields: [
                "quantity",
                "unit_budget_cny",
                "max_total_power_w",
              ],
            },
          ],
        },
      },
    },
  ],
  docModels: [
    {
      exprId: "exp-pc-document",
      docNo: "PC-PROCUREMENT-PLAN",
      template: "电脑采购方案说明书",
      binding: { objectId: "pc-ref-valid-plan" },
      authorLine: "采购工作台 · 数据来自当前工作空间",
      blocks: [
        {
          kind: "meta",
          items: ["电脑采购", "模板:采购方案说明书", "绑定:装机方案"],
        },
        {
          kind: "h1",
          text: "采购方案 · {{ref}}",
          refId: "ref-pc-plan-name",
        },
        { kind: "h2", text: "一、方案概况" },
        {
          kind: "paragraph",
          id: "pc-plan-summary",
          inlines: [
            { kind: "text", text: "方案编码 " },
            { kind: "ref", refId: "ref-pc-plan-code" },
            { kind: "text", text: "，当前生命周期状态为 " },
            { kind: "ref", refId: "ref-pc-plan-status" },
            { kind: "text", text: "。" },
          ],
        },
        { kind: "h2", text: "二、成本与性能" },
        {
          kind: "dataTable",
          id: "pc-plan-metrics",
          title: "方案指标",
          sourceLabel: "装机方案",
          rows: [
            { label: "方案总价", refId: "ref-pc-plan-price" },
            { label: "方案总功耗", refId: "ref-pc-plan-power" },
            { label: "方案性能分", refId: "ref-pc-plan-performance" },
          ],
        },
      ],
    },
  ],
  fieldRefs: [
    {
      id: "ref-pc-plan-name",
      objectId: "pc-ref-valid-plan",
      fieldCode: "name",
      exprId: "exp-pc-document",
      label: "方案名称",
      state: "fresh",
    },
    {
      id: "ref-pc-plan-code",
      objectId: "pc-ref-valid-plan",
      fieldCode: "code",
      exprId: "exp-pc-document",
      label: "方案编码",
      state: "fresh",
    },
    {
      id: "ref-pc-plan-status",
      objectId: "pc-ref-valid-plan",
      fieldCode: "status",
      exprId: "exp-pc-document",
      label: "生命周期状态",
      state: "fresh",
    },
    {
      id: "ref-pc-plan-price",
      objectId: "pc-ref-valid-plan",
      fieldCode: "total_price_cny_fx",
      exprId: "exp-pc-document",
      label: "方案总价",
      state: "fresh",
    },
    {
      id: "ref-pc-plan-power",
      objectId: "pc-ref-valid-plan",
      fieldCode: "total_power_w_fx",
      exprId: "exp-pc-document",
      label: "方案总功耗",
      state: "fresh",
    },
    {
      id: "ref-pc-plan-performance",
      objectId: "pc-ref-valid-plan",
      fieldCode: "total_performance_score_fx",
      exprId: "exp-pc-document",
      label: "方案性能分",
      state: "fresh",
    },
  ],
  kpis: [
    {
      id: "kpi-pc-budget",
      label: "需求预算",
      value: "—",
      delta: "工作空间派生",
      deltaSign: "flat",
      sourceLabel: "采购需求",
      visible: true,
    },
    {
      id: "kpi-pc-price",
      label: "方案总价",
      value: "—",
      delta: "供应商报价口径",
      deltaSign: "flat",
      sourceLabel: "装机方案",
      visible: true,
    },
    {
      id: "kpi-pc-power",
      label: "方案总功耗",
      value: "—",
      delta: "含 20% 电源余量校验",
      deltaSign: "flat",
      sourceLabel: "装机方案",
      visible: true,
    },
    {
      id: "kpi-pc-performance",
      label: "方案性能分",
      value: "—",
      delta: "配件性能汇总",
      deltaSign: "flat",
      sourceLabel: "装机方案",
      visible: true,
    },
  ],
  biBars: [],
  anaReports: [
    {
      id: "ana-pc-plan-comparison",
      viewId: "view-pc-ana",
      scopeLabel: "当前电脑采购工作空间",
      question: "方案在预算、兼容性、功耗与性能上有何差异？",
      sourcesLabel: "采购需求 + 装机方案 + 供应商报价",
      factorTitle: "方案因素",
      factorMetricLabel: "当前预设未提供分析算法",
      factors: [],
      drillTitle: "方案明细",
      drillTraceLabel: "数据来自当前工作空间",
      drillColumns: [],
      drillRows: [],
      insights: [
        {
          title: "规则口径",
          segments: [
            { text: "有效性由规则结果决定，生命周期状态不表示校验结论。" },
          ],
        },
      ],
      pinKpiId: "kpi-pc-price",
      childKpiIds: ["kpi-pc-power", "kpi-pc-performance"],
      childActionLabel: "生成指标子看板",
    },
  ],
  slotBindings: [],
  objectBindings: [
    {
      presentationId: "pc-ref-requirement",
      objectTypeCode: "procurement_requirement",
      fields: { code: "REQ-DEV-A" },
    },
    {
      presentationId: "pc-ref-valid-plan",
      objectTypeCode: "build_plan",
      fields: { code: "PLAN-STD", name: "标准开发配置(约8000元)" },
    },
    {
      presentationId: "pc-ref-invalid-plan",
      objectTypeCode: "build_plan",
      fields: { code: "PLAN-PRO", name: "高级开发配置(约12000元)" },
    },
    {
      presentationId: "pc-ref-valid-cpu-item",
      objectTypeCode: "build_plan_item",
      fields: { code: "ITEM-STD-CPU" },
    },
    {
      presentationId: "pc-ref-valid-cpu-product",
      objectTypeCode: "hardware_product",
      fields: { code: "HW-CPU-ULTRA7-265" },
    },
    {
      presentationId: "pc-ref-valid-cpu-quote",
      objectTypeCode: "supplier_quote",
      fields: { code: "Q-CPU-ULTRA7-265" },
    },
  ],
  relationBindings: [
    {
      presentationId: "pc-rel-valid-satisfies",
      relationTypeCode: "build_plan_satisfies_requirement",
      sourceId: "pc-ref-valid-plan",
      targetId: "pc-ref-requirement",
    },
    {
      presentationId: "pc-rel-invalid-satisfies",
      relationTypeCode: "build_plan_satisfies_requirement",
      sourceId: "pc-ref-invalid-plan",
      targetId: "pc-ref-requirement",
    },
    {
      presentationId: "pc-rel-valid-contains-cpu",
      relationTypeCode: "build_plan_contains_item",
      sourceId: "pc-ref-valid-plan",
      targetId: "pc-ref-valid-cpu-item",
    },
    {
      presentationId: "pc-rel-valid-cpu-selects-product",
      relationTypeCode: "build_plan_item_selects_product",
      sourceId: "pc-ref-valid-cpu-item",
      targetId: "pc-ref-valid-cpu-product",
    },
    {
      presentationId: "pc-rel-valid-cpu-uses-quote",
      relationTypeCode: "build_plan_item_uses_supplier_quote",
      sourceId: "pc-ref-valid-cpu-item",
      targetId: "pc-ref-valid-cpu-quote",
    },
    {
      presentationId: "pc-rel-valid-cpu-quote-for-product",
      relationTypeCode: "supplier_quote_for_product",
      sourceId: "pc-ref-valid-cpu-quote",
      targetId: "pc-ref-valid-cpu-product",
    },
  ],
};
