import type {
  ChangeSet,
  Comment,
  DataFieldPrimitive,
  DataFieldValue,
  DataObject,
  DataRelation,
  ObjectTypeDef,
  OutputSnapshot,
  PermissionMatrix,
  RelationType,
  ReviewRecord,
  SceneTemplate,
  ViewDef,
  Workspace,
} from "../model/kernel";
import type {
  ActivityItem,
  AnaReport,
  BiBarDef,
  ChangeEvent,
  ChatMessage,
  DocModel,
  Expression,
  FieldRef,
  KpiCardDef,
  Member,
  PluginDef,
  RawImport,
  SimScenario,
  SlotBinding,
} from "../model/view-layer";

const at = {
  baseline: "2026-07-10T09:12:00+08:00",
  import: "2026-07-10T10:18:00+08:00",
  confirmed: "2026-07-10T10:24:00+08:00",
  validation: "2026-07-10T10:32:00+08:00",
} as const;

function fv(
  value: DataFieldPrimitive,
  fieldVersion = 1,
  source: "manual" | "ai" = "manual",
): DataFieldValue {
  return {
    value,
    fieldVersion,
    updatedBy: source === "ai" ? "ai" : "wangyun",
    updatedAt: at.confirmed,
    source,
  };
}

function dataObject(params: {
  readonly id: string;
  readonly objectTypeCode: string;
  readonly status?: DataObject["status"];
  readonly fields: Record<string, DataFieldPrimitive>;
  readonly source?: "manual" | "ai";
}): DataObject {
  return {
    id: params.id,
    objectTypeCode: params.objectTypeCode,
    status: params.status ?? "active",
    version: 1,
    fields: Object.fromEntries(
      Object.entries(params.fields).map(([code, value]) => [
        code,
        fv(value, 1, params.source),
      ]),
    ),
    createdBy: params.source === "ai" ? "ai" : "wangyun",
    createdAt: at.baseline,
    updatedBy: params.source === "ai" ? "ai" : "wangyun",
    updatedAt: at.confirmed,
  };
}

export interface DemoSeed {
  readonly workspace: Workspace;
  readonly members: readonly Member[];
  readonly objectTypes: readonly ObjectTypeDef[];
  readonly objects: readonly DataObject[];
  readonly relationTypes: readonly RelationType[];
  readonly relations: readonly DataRelation[];
  readonly comments: readonly Comment[];
  readonly permissions: PermissionMatrix;
  readonly sceneTemplates: readonly SceneTemplate[];
  readonly expressions: readonly Expression[];
  readonly views: readonly ViewDef[];
  readonly docModels: readonly DocModel[];
  readonly fieldRefs: readonly FieldRef[];
  readonly kpis: readonly KpiCardDef[];
  readonly biBars: readonly BiBarDef[];
  readonly anaReports: readonly AnaReport[];
  readonly rawImport: RawImport;
  readonly chatMessages: readonly ChatMessage[];
  readonly reviewRecords: readonly ReviewRecord[];
  readonly slotBindings: readonly SlotBinding[];
  readonly changeSets: readonly ChangeSet[];
  readonly changeEvents: readonly ChangeEvent[];
  readonly activity: readonly ActivityItem[];
  readonly outputSnapshots: readonly OutputSnapshot[];
  readonly plugins: readonly PluginDef[];
  readonly simScenarios: readonly SimScenario[];
}

export const productType: ObjectTypeDef = {
  code: "product_specs",
  name: "产品规格库",
  group: "产品中心",
  fields: [
    { code: "sku", name: "产品编号", dataType: "text" },
    { code: "name", name: "名称", dataType: "text" },
    { code: "price", name: "权威售价", dataType: "number", unit: "CNY" },
    { code: "owner", name: "负责人", dataType: "person" },
    { code: "battery_months", name: "续航(月)", dataType: "number" },
    { code: "rating", name: "防护等级", dataType: "text" },
    { code: "launch_date", name: "上市日期", dataType: "date" },
    {
      code: "lifecycle",
      name: "状态",
      dataType: "enum",
      enumValues: ["研发中", "预售", "在售", "停产"],
    },
  ],
};

export const hardwareType: ObjectTypeDef = {
  code: "hardware_products",
  name: "硬件产品库",
  group: "供应链",
  fields: [
    { code: "name", name: "名称", dataType: "text" },
    {
      code: "part_type",
      name: "品类",
      dataType: "enum",
      enumValues: ["主板", "CPU", "电源", "内存", "显卡"],
    },
    { code: "chipset", name: "芯片组", dataType: "text" },
    {
      code: "form_factor",
      name: "版型",
      dataType: "enum",
      enumValues: ["ATX", "mATX"],
    },
    { code: "socket", name: "插槽", dataType: "text" },
    { code: "vrm", name: "供电", dataType: "text" },
    { code: "price", name: "价格", dataType: "number", unit: "CNY" },
    { code: "cores", name: "核心数", dataType: "number" },
  ],
};

export const objectTypes: readonly ObjectTypeDef[] = [
  productType,
  hardwareType,
  {
    code: "channel_sales",
    name: "渠道销量表",
    group: "销售中心",
    fields: [
      { code: "channel", name: "渠道", dataType: "text" },
      { code: "month_sales", name: "本月销量", dataType: "number" },
      { code: "cached_price", name: "S3 售价缓存", dataType: "number" },
    ],
  },
  {
    code: "contracts",
    name: "合同台账",
    group: "产品中心",
    fields: [
      { code: "name", name: "合同名称", dataType: "text" },
      { code: "product", name: "产品", dataType: "text" },
      { code: "channel", name: "渠道", dataType: "text" },
      { code: "quote", name: "报价", dataType: "number", unit: "CNY" },
      { code: "contact", name: "联系人", dataType: "text" },
      { code: "amount", name: "金额", dataType: "number", unit: "CNY" },
    ],
  },
  {
    code: "customers",
    name: "客户信息库",
    group: "客户中心",
    fields: [
      { code: "name", name: "客户名称", dataType: "text" },
      { code: "region", name: "区域", dataType: "text" },
    ],
  },
];

const products: readonly DataObject[] = [
  dataObject({
    id: "prod-s3",
    objectTypeCode: "product_specs",
    status: "presale",
    fields: {
      sku: "DL-S3-2026",
      name: "门锁 S3",
      price: 1199,
      owner: "wangyun",
      battery_months: 14,
      rating: "IP65",
      launch_date: "2026-08-18",
      lifecycle: "预售",
    },
  }),
  dataObject({
    id: "prod-s3-lite",
    objectTypeCode: "product_specs",
    status: "dev",
    fields: {
      sku: "DL-S3-LITE",
      name: "门锁 S3 Lite",
      price: 899,
      owner: "lixiao",
      battery_months: 12,
      rating: "IP54",
      launch_date: null,
      lifecycle: "研发中",
    },
  }),
  dataObject({
    id: "prod-d2-pro",
    objectTypeCode: "product_specs",
    status: "presale",
    fields: {
      sku: "DB-D2-PRO",
      name: "门铃 D2 Pro",
      price: 599,
      owner: "chenmo",
      battery_months: 8,
      rating: "IP54",
      launch_date: "2026-09-10",
      lifecycle: "预售",
    },
  }),
  dataObject({
    id: "prod-d2",
    objectTypeCode: "product_specs",
    status: "sale",
    fields: {
      sku: "DB-D2",
      name: "门铃 D2",
      price: 399,
      owner: "chenmo",
      battery_months: 6,
      rating: "IP54",
      launch_date: "2025-11-02",
      lifecycle: "在售",
    },
  }),
  dataObject({
    id: "prod-e1",
    objectTypeCode: "product_specs",
    status: "sale",
    fields: {
      sku: "EYE-E1",
      name: "猫眼 E1",
      price: 699,
      owner: "wangyun",
      battery_months: 10,
      rating: "IP54",
      launch_date: "2026-03-20",
      lifecycle: "在售",
    },
  }),
  dataObject({
    id: "prod-g2",
    objectTypeCode: "product_specs",
    status: "sale",
    fields: {
      sku: "GW-G2",
      name: "网关 G2",
      price: 199,
      owner: "wangyun",
      battery_months: 0,
      rating: "Indoor",
      launch_date: "2025-08-18",
      lifecycle: "在售",
    },
  }),
  dataObject({
    id: "prod-m1",
    objectTypeCode: "product_specs",
    status: "sale",
    fields: {
      sku: "MAG-M1",
      name: "门磁 M1",
      price: 79,
      owner: "lixiao",
      battery_months: 18,
      rating: "IP54",
      launch_date: "2025-05-12",
      lifecycle: "在售",
    },
  }),
  dataObject({
    id: "prod-p1",
    objectTypeCode: "product_specs",
    status: "eol",
    fields: {
      sku: "LOCK-P1",
      name: "挂锁 P1",
      price: 299,
      owner: "zhouran",
      battery_months: 10,
      rating: "IP54",
      launch_date: "2024-09-01",
      lifecycle: "停产",
    },
  }),
];

const channelSales: readonly DataObject[] = Array.from({ length: 42 }, (_, i) =>
  dataObject({
    id: i === 0 ? "sales-offline-dealer" : `sales-channel-${i + 1}`,
    objectTypeCode: "channel_sales",
    fields: {
      channel:
        i === 0 ? "线下经销" : `区域渠道 ${String(i + 1).padStart(2, "0")}`,
      month_sales: i === 0 ? 2850 : 120 + i * 7,
      cached_price: i === 0 ? 1299 : 1199,
    },
  }),
);

const contractObjects: readonly DataObject[] = [
  dataObject({
    id: "contract-east-s3",
    objectTypeCode: "contracts",
    source: "ai",
    fields: {
      name: "华东智联 · S3 报价",
      product: "门锁 S3",
      channel: "华东经销",
      quote: 1199,
      contact: "老李 138****8000",
      amount: 880000,
    },
  }),
  dataObject({
    id: "contract-north-d2",
    objectTypeCode: "contracts",
    fields: { name: "北区门铃补货", product: "门铃 D2", amount: 240000 },
  }),
];

const customerObjects: readonly DataObject[] = [
  dataObject({
    id: "customer-east",
    objectTypeCode: "customers",
    fields: { name: "华东智联", region: "华东" },
  }),
  dataObject({
    id: "customer-south",
    objectTypeCode: "customers",
    fields: { name: "南区渠道联合体", region: "华南" },
  }),
];

const hardwareObjects: readonly DataObject[] = [
  dataObject({
    id: "hw-mb-rog-z890-hero",
    objectTypeCode: "hardware_products",
    fields: {
      name: "ROG Maximus Z890 Hero",
      part_type: "主板",
      chipset: "Z890",
      form_factor: "ATX",
      socket: "LGA1851",
      vrm: "22+1+2",
      price: 5299,
      cores: null,
    },
  }),
  dataObject({
    id: "hw-mb-strix-z890-e",
    objectTypeCode: "hardware_products",
    fields: {
      name: "ROG Strix Z890-E",
      part_type: "主板",
      chipset: "Z890",
      form_factor: "ATX",
      socket: "LGA1851",
      vrm: "18+1+2",
      price: 3999,
      cores: null,
    },
  }),
  dataObject({
    id: "hw-mb-tuf-z890-plus",
    objectTypeCode: "hardware_products",
    fields: {
      name: "TUF Z890-Plus",
      part_type: "主板",
      chipset: "Z890",
      form_factor: "ATX",
      socket: "LGA1851",
      vrm: "16+1+1",
      price: 2599,
      cores: null,
    },
  }),
  dataObject({
    id: "hw-mb-prime-z890-p",
    objectTypeCode: "hardware_products",
    fields: {
      name: "Prime Z890-P",
      part_type: "主板",
      chipset: "Z890",
      form_factor: "ATX",
      socket: "LGA1851",
      vrm: "14+1+1",
      price: 1999,
      cores: null,
    },
  }),
  dataObject({
    id: "hw-mb-tuf-b860-plus",
    objectTypeCode: "hardware_products",
    fields: {
      name: "TUF B860-Plus",
      part_type: "主板",
      chipset: "B860",
      form_factor: "ATX",
      socket: "LGA1851",
      vrm: "12+1+1",
      price: 1599,
      cores: null,
    },
  }),
  dataObject({
    id: "hw-mb-prime-b860m-a",
    objectTypeCode: "hardware_products",
    fields: {
      name: "Prime B860M-A",
      part_type: "主板",
      chipset: "B860",
      form_factor: "mATX",
      socket: "LGA1851",
      vrm: "8+1+1",
      price: 1299,
      cores: null,
    },
  }),
  dataObject({
    id: "hw-cpu-ultra7-265k",
    objectTypeCode: "hardware_products",
    fields: {
      name: "Intel Core Ultra 7 265K",
      part_type: "CPU",
      chipset: "",
      form_factor: "",
      socket: "LGA1851",
      vrm: "",
      price: 2899,
      cores: 20,
    },
  }),
  dataObject({
    id: "hw-psu-850-gold",
    objectTypeCode: "hardware_products",
    fields: {
      name: "ROG 850W Gold",
      part_type: "电源",
      chipset: "",
      form_factor: "ATX",
      socket: "",
      vrm: "",
      price: 899,
      cores: null,
    },
  }),
  dataObject({
    id: "hw-ram-ddr5-32",
    objectTypeCode: "hardware_products",
    fields: {
      name: "DDR5 32GB 6400",
      part_type: "内存",
      chipset: "DDR5",
      form_factor: "",
      socket: "",
      vrm: "",
      price: 699,
      cores: null,
    },
  }),
  dataObject({
    id: "hw-ram-ddr4-32",
    objectTypeCode: "hardware_products",
    fields: {
      name: "DDR4 32GB 3600",
      part_type: "内存",
      chipset: "DDR4",
      form_factor: "",
      socket: "",
      vrm: "",
      price: 399,
      cores: null,
    },
  }),
  dataObject({
    id: "hw-gpu-rtx5070",
    objectTypeCode: "hardware_products",
    fields: {
      name: "GeForce RTX 5070",
      part_type: "显卡",
      chipset: "PCIe 5.0",
      form_factor: "",
      socket: "",
      vrm: "",
      price: 4299,
      cores: null,
    },
  }),
  dataObject({
    id: "hw-gpu-pcie4-4060",
    objectTypeCode: "hardware_products",
    fields: {
      name: "GeForce RTX 4060 PCIe4",
      part_type: "显卡",
      chipset: "PCIe 4.0",
      form_factor: "",
      socket: "",
      vrm: "",
      price: 2199,
      cores: null,
    },
  }),
];

const rawImportText =
  "老李发来华东经销报价: 门锁 S3 建议售价 1199 元,联系人 138****8000,上市日期可能是 8 月 18 日。防护等级 IP65 不变。";

function rawSpan(
  needle: string,
  tone: "primary" | "change",
): {
  readonly start: number;
  readonly end: number;
  readonly tone: "primary" | "change";
} {
  const start = rawImportText.indexOf(needle);
  return { start, end: start + needle.length, tone };
}

export const demoSeed: DemoSeed = {
  workspace: {
    id: "ws-unisource-demo",
    name: "智能硬件团队",
    currentMemberId: "wangyun",
    updatedAt: at.validation,
  },
  members: [
    {
      id: "wangyun",
      name: "王芸",
      role: "管理员",
      dept: "产品部",
      email: "wang@team.cn",
      avatar: "wang",
    },
    {
      id: "lixiao",
      name: "李晓",
      role: "研发",
      dept: "研发部",
      email: "li@team.cn",
      avatar: "li",
    },
    {
      id: "chenmo",
      name: "陈默",
      role: "渠道运营",
      dept: "渠道运营",
      email: "chen@team.cn",
      avatar: "chen",
    },
    {
      id: "zhouran",
      name: "周然",
      role: "法务",
      dept: "法务部",
      email: "zhou@team.cn",
      avatar: "zhou",
    },
    {
      id: "ai",
      name: "同源 AI",
      role: "代理",
      dept: "系统代理",
      email: "ai@team.cn",
      avatar: "ai",
    },
  ],
  objectTypes,
  objects: [
    ...products,
    ...hardwareObjects,
    ...channelSales,
    ...contractObjects,
    ...customerObjects,
  ],
  relationTypes: [
    {
      code: "interconnects_with",
      name: "互联",
      sourceTypeCode: "product_specs",
      targetTypeCode: "product_specs",
    },
  ],
  relations: [
    {
      id: "rel-s3-g2-interconnect",
      relationTypeCode: "interconnects_with",
      sourceId: "prod-s3",
      targetId: "prod-g2",
      status: "active",
      fields: {
        protocol: fv("Matter + BLE"),
        scenario: fv("全屋门户方案"),
      },
      version: 1,
      annotationIds: ["comment-rel-s3-g2"],
    },
    {
      id: "rel-d2pro-g2-interconnect",
      relationTypeCode: "interconnects_with",
      sourceId: "prod-d2-pro",
      targetId: "prod-g2",
      status: "active",
      fields: {
        protocol: fv("推送"),
        scenario: fv("全屋门户方案"),
      },
      version: 1,
      annotationIds: [],
    },
    {
      id: "rel-e1-g2-interconnect",
      relationTypeCode: "interconnects_with",
      sourceId: "prod-e1",
      targetId: "prod-g2",
      status: "active",
      fields: {
        protocol: fv("联动录像"),
        scenario: fv("全屋门户方案"),
      },
      version: 1,
      annotationIds: [],
    },
  ],
  comments: [
    {
      id: "comment-rel-s3-g2",
      anchor: { entityType: "relation", entityId: "rel-s3-g2-interconnect" },
      body: "S3 与网关 G2 的互联协议需在供货协议中保留。",
      author: "lixiao",
      at: at.confirmed,
      resolved: false,
    },
  ],
  permissions: {
    wangyun: {
      product_specs: "admin",
      hardware_products: "admin",
      customers: "admin",
      channel_sales: "admin",
      "exp-dashboard": "edit",
      "exp-spec-doc": "owner",
      "exp-portal": "edit",
      "exp-build-z890": "edit",
      "exp-build-b860": "edit",
      "exp-build-z890-doc": "edit",
      "exp-build-b860-doc": "edit",
    },
    lixiao: {
      product_specs: "edit",
      hardware_products: "edit",
      customers: "none",
      channel_sales: "readonly",
      "exp-dashboard": "readonly",
      "exp-spec-doc": "edit",
      "exp-portal": "edit",
      "exp-build-z890": "edit",
      "exp-build-b860": "edit",
      "exp-build-z890-doc": "edit",
      "exp-build-b860-doc": "edit",
    },
    chenmo: {
      product_specs: "readonly",
      hardware_products: "readonly",
      customers: "none",
      channel_sales: "edit",
      "exp-dashboard": "edit",
      "exp-spec-doc": "readonly",
      "exp-portal": "edit",
      "exp-build-z890": "readonly",
      "exp-build-b860": "readonly",
      "exp-build-z890-doc": "readonly",
      "exp-build-b860-doc": "readonly",
    },
    zhouran: {
      product_specs: "readonly",
      hardware_products: "readonly",
      customers: "none",
      channel_sales: "none",
      "exp-dashboard": "none",
      "exp-spec-doc": "readonly",
      "exp-portal": "readonly",
      "exp-build-z890": "readonly",
      "exp-build-b860": "readonly",
      "exp-build-z890-doc": "readonly",
      "exp-build-b860-doc": "readonly",
    },
    ai: {},
  },
  sceneTemplates: [
    {
      id: "tpl-install-v1",
      name: "装机方案 V1",
      version: "1.0",
      slots: [
        {
          id: "slot-cpu",
          abstractType: "cpu",
          label: "CPU",
          constraints: [
            { field: "part_type", op: "eq", value: "CPU" },
            { field: "socket", op: "eq", value: "LGA1851" },
          ],
          constraintLabels: ["LGA1851", "20C 推荐"],
          shownFields: ["socket", "cores", "price"],
          connectsTo: ["slot-mainboard"],
        },
        {
          id: "slot-psu",
          abstractType: "power",
          label: "电源",
          constraints: [{ field: "part_type", op: "eq", value: "电源" }],
          constraintLabels: ["ATX 电源"],
          shownFields: ["price"],
        },
        {
          id: "slot-mainboard",
          abstractType: "mainboard",
          label: "主板",
          constraints: [
            { field: "part_type", op: "eq", value: "主板" },
            { field: "socket", op: "eq", value: "LGA1851" },
            { field: "form_factor", op: "eq", value: "ATX" },
          ],
          constraintLabels: ["LGA1851", "ATX"],
          shownFields: ["chipset", "form_factor", "vrm", "price"],
          connectsTo: ["slot-memory", "slot-gpu"],
        },
        {
          id: "slot-memory",
          abstractType: "memory",
          label: "内存 ×2",
          constraints: [
            { field: "part_type", op: "eq", value: "内存" },
            { field: "chipset", op: "eq", value: "DDR5" },
          ],
          constraintLabels: ["DDR5"],
          shownFields: ["chipset", "price"],
        },
        {
          id: "slot-gpu",
          abstractType: "gpu",
          label: "显卡",
          constraints: [
            { field: "part_type", op: "eq", value: "显卡" },
            { field: "chipset", op: "eq", value: "PCIe 5.0" },
          ],
          constraintLabels: ["PCIe"],
          shownFields: ["chipset", "price"],
        },
      ],
    },
  ],
  expressions: [
    {
      id: "exp-dashboard",
      name: "渠道经营看板",
      viewIds: [
        "view-dashboard-bi",
        "view-dashboard-grid",
        "view-dashboard-doc",
        "view-dashboard-ana",
      ],
      defaultViewId: "view-dashboard-bi",
      defaultForm: "bi",
      activityMember: "wangyun",
      lastActivity: "续航 12→14 + 看板加卡",
    },
    {
      id: "exp-spec-doc",
      name: "智能门锁 S3 产品规格书",
      viewIds: ["view-spec-doc", "view-spec-grid"],
      defaultViewId: "view-spec-doc",
      defaultForm: "doc",
      activityMember: "wangyun",
      lastActivity: "售价同步为 ¥1,199",
    },
    {
      id: "exp-agreement",
      name: "经销商供货协议·华东",
      viewIds: ["view-agreement-doc", "view-agreement-grid"],
      defaultViewId: "view-agreement-doc",
      defaultForm: "doc",
      activityMember: "lixiao",
      lastActivity: "AI 导入新增报价合同",
    },
    {
      id: "exp-weekly",
      name: "Q3 渠道周报",
      viewIds: ["view-weekly-doc", "view-weekly-bi"],
      defaultViewId: "view-weekly-doc",
      defaultForm: "doc",
      activityMember: "chenmo",
      lastActivity: "渠道销量缓存待修复",
    },
    {
      id: "exp-portal",
      name: "全屋智能门户方案",
      viewIds: ["view-portal-canvas"],
      defaultViewId: "view-portal-canvas",
      defaultForm: "canvas",
      activityMember: "chenmo",
      lastActivity: "S3 与 G2 建立互联",
    },
    {
      id: "exp-build-z890",
      name: "装机方案·Z890 高配",
      space: "workshop",
      viewIds: ["view-build-z890-canvas"],
      defaultViewId: "view-build-z890-canvas",
      defaultForm: "canvas",
      activityMember: "lixiao",
      lastActivity: "模板槽位待实例化",
    },
    {
      id: "exp-build-b860",
      name: "装机方案·B860 性价比",
      space: "workshop",
      viewIds: ["view-build-b860-canvas"],
      defaultViewId: "view-build-b860-canvas",
      defaultForm: "canvas",
      activityMember: "lixiao",
      lastActivity: "主板槽触发版型告警",
    },
    {
      id: "exp-build-z890-doc",
      name: "装机配置单·Z890",
      space: "workshop",
      viewIds: ["view-build-z890-doc"],
      defaultViewId: "view-build-z890-doc",
      defaultForm: "doc",
      activityMember: "wangyun",
      lastActivity: "等待槽位实例化",
    },
    {
      id: "exp-build-b860-doc",
      name: "装机配置单·B860",
      space: "workshop",
      viewIds: ["view-build-b860-doc"],
      defaultViewId: "view-build-b860-doc",
      defaultForm: "doc",
      activityMember: "wangyun",
      lastActivity: "等待槽位实例化",
    },
    {
      id: "exp-inventory",
      name: "产品状态盘点",
      viewIds: ["view-inventory-matrix"],
      defaultViewId: "view-inventory-matrix",
      defaultForm: "matrix",
      activityMember: "wangyun",
      lastActivity: "停产列透明显示",
    },
  ],
  views: [
    {
      id: "view-dashboard-bi",
      exprId: "exp-dashboard",
      kind: "bi",
      config: {
        title: "各渠道销量 · 本月",
        sourceLabel: "渠道销量表",
        emptyLabel: "暂无渠道销量数据",
        objectTypeCodes: ["product_specs"],
      },
    },
    {
      id: "view-dashboard-grid",
      exprId: "exp-dashboard",
      kind: "grid",
      config: {},
    },
    {
      id: "view-dashboard-doc",
      exprId: "exp-dashboard",
      kind: "doc",
      config: {},
    },
    {
      id: "view-dashboard-ana",
      exprId: "exp-dashboard",
      kind: "ana",
      config: { reportId: "ana-aov-july", allowReanalysis: true },
    },
    { id: "view-spec-doc", exprId: "exp-spec-doc", kind: "doc", config: {} },
    { id: "view-spec-grid", exprId: "exp-spec-doc", kind: "grid", config: {} },
    {
      id: "view-agreement-doc",
      exprId: "exp-agreement",
      kind: "doc",
      config: {},
    },
    {
      id: "view-agreement-grid",
      exprId: "exp-agreement",
      kind: "grid",
      config: {},
    },
    { id: "view-weekly-doc", exprId: "exp-weekly", kind: "doc", config: {} },
    {
      id: "view-weekly-bi",
      exprId: "exp-weekly",
      kind: "bi",
      config: {
        title: "各渠道销量 · 本月",
        sourceLabel: "渠道销量表",
        emptyLabel: "暂无渠道销量数据",
      },
    },
    {
      id: "view-portal-canvas",
      exprId: "exp-portal",
      kind: "canvas",
      config: {
        nodes: [
          {
            objectId: "prod-d2-pro",
            x: 120,
            y: 104,
            w: 210,
            h: 124,
            shownFields: ["price", "battery_months"],
          },
          {
            objectId: "prod-s3",
            x: 590,
            y: 96,
            w: 210,
            h: 124,
            shownFields: ["price", "battery_months"],
          },
          {
            objectId: "prod-e1",
            x: 150,
            y: 344,
            w: 210,
            h: 124,
            shownFields: ["price", "battery_months"],
          },
          {
            objectId: "prod-g2",
            x: 410,
            y: 252,
            w: 210,
            h: 124,
            shownFields: ["price", "rating"],
          },
        ],
        edges: [
          { relationId: "rel-s3-g2-interconnect" },
          { relationId: "rel-d2pro-g2-interconnect" },
          { relationId: "rel-e1-g2-interconnect" },
        ],
      },
    },
    {
      id: "view-build-z890-canvas",
      exprId: "exp-build-z890",
      kind: "canvas",
      config: {
        templateId: "tpl-install-v1",
        libraryObjectTypeCode: "hardware_products",
        libraryCategoryFieldCode: "part_type",
        librarySpecFieldCodes: ["chipset", "form_factor", "vrm", "socket"],
        libraryValueFieldCode: "price",
        libraryGroupFieldCode: "chipset",
        outputFileBaseName: "装机配置单",
        libraryFooter: "点击或拖入槽位即可实例化。字段随硬件产品库更新。",
        hint: "模板只保存抽象槽位；拖入库记录后，字段随硬件产品库更新。",
        edgeLabels: {
          "slot-cpu:slot-mainboard": "socket",
          "slot-mainboard:slot-memory": "DDR5",
          "slot-mainboard:slot-gpu": "PCIe",
          "slot-psu:slot-mainboard": "结构",
        },
        slotNodes: [
          { slotId: "slot-cpu", x: 120, y: 96 },
          { slotId: "slot-mainboard", x: 420, y: 96 },
          { slotId: "slot-memory", x: 720, y: 80 },
          { slotId: "slot-gpu", x: 720, y: 260 },
          { slotId: "slot-psu", x: 120, y: 288 },
        ],
      },
    },
    {
      id: "view-build-b860-canvas",
      exprId: "exp-build-b860",
      kind: "canvas",
      config: {
        templateId: "tpl-install-v1",
        libraryObjectTypeCode: "hardware_products",
        libraryCategoryFieldCode: "part_type",
        librarySpecFieldCodes: ["chipset", "form_factor", "vrm", "socket"],
        libraryValueFieldCode: "price",
        libraryGroupFieldCode: "chipset",
        outputFileBaseName: "装机配置单",
        libraryFooter: "点击或拖入槽位即可实例化。字段随硬件产品库更新。",
        hint: "模板只保存抽象槽位；拖入库记录后，字段随硬件产品库更新。",
        edgeLabels: {
          "slot-cpu:slot-mainboard": "socket",
          "slot-mainboard:slot-memory": "DDR5",
          "slot-mainboard:slot-gpu": "PCIe",
          "slot-psu:slot-mainboard": "结构",
        },
        slotNodes: [
          { slotId: "slot-cpu", x: 120, y: 96 },
          { slotId: "slot-mainboard", x: 420, y: 96 },
          { slotId: "slot-memory", x: 720, y: 80 },
          { slotId: "slot-gpu", x: 720, y: 260 },
          { slotId: "slot-psu", x: 120, y: 288 },
        ],
      },
    },
    {
      id: "view-build-z890-doc",
      exprId: "exp-build-z890-doc",
      kind: "doc",
      config: {
        sourceExprId: "exp-build-z890",
        templateId: "tpl-install-v1",
        documentNo: "BUILD-Z890-001",
        title: "装机配置单·Z890",
        authorLine: "王芸 · 供应链 | 字段来自硬件产品库",
        intro:
          "本配置单由模板槽位实时生成。任一硬件产品库字段更新后，价格与合计同步刷新。",
        tableTitle: "配置明细 · 来自槽位绑定",
        nameFieldCode: "name",
        valueFieldCode: "price",
        totalLabel: "合计",
        totalPrefix: "¥",
      },
    },
    {
      id: "view-build-b860-doc",
      exprId: "exp-build-b860-doc",
      kind: "doc",
      config: {
        sourceExprId: "exp-build-b860",
        templateId: "tpl-install-v1",
        documentNo: "BUILD-B860-001",
        title: "装机配置单·B860",
        authorLine: "王芸 · 供应链 | 字段来自硬件产品库",
        intro:
          "本配置单由模板槽位实时生成。任一硬件产品库字段更新后，价格与合计同步刷新。",
        tableTitle: "配置明细 · 来自槽位绑定",
        nameFieldCode: "name",
        valueFieldCode: "price",
        totalLabel: "合计",
        totalPrefix: "¥",
      },
    },
    {
      id: "view-inventory-matrix",
      exprId: "exp-inventory",
      kind: "matrix",
      config: {
        sourceTypeCode: "product_specs",
        rowField: "owner",
        colField: "lifecycle",
        cardFields: ["price", "docRefs"],
        summary: "count",
        allowColumnMove: true,
        dimValues: ["停产"],
        interactionHint:
          "矩阵即描述形式:拖动卡片跨列 = 修改『状态』字段,表格与所有文档引用同步更新。",
      },
    },
  ],
  docModels: [
    {
      exprId: "exp-spec-doc",
      docNo: "SPEC-2026-018",
      template: "产品规格书 V2",
      binding: { objectId: "prod-s3" },
      authorLine: "王芸 · 产品部 | 更新于今天 09:12",
      blocks: [
        {
          kind: "meta",
          items: [
            "SPEC-2026-018",
            "模板:产品规格书 V2",
            "绑定:产品规格库 › 智能门锁 S3",
          ],
        },
        {
          kind: "h1",
          text: "智能门锁 S3 产品规格书",
          refId: "ref-s3-name-title",
        },
        { kind: "h2", text: "一、定位与定价" },
        {
          kind: "paragraph",
          id: "p-position",
          inlines: [
            { kind: "text", text: "本规格书描述 " },
            { kind: "ref", refId: "ref-s3-name-position" },
            { kind: "text", text: " 的上市定位。型号 " },
            { kind: "ref", refId: "ref-s3-sku-hero" },
            { kind: "text", text: " 面向高端入户门场景,建议零售价为 " },
            { kind: "ref", refId: "ref-s3-price-spec" },
            { kind: "text", text: "。" },
          ],
        },
        {
          kind: "paragraph",
          id: "p-status",
          inlines: [
            { kind: "text", text: "当前生命周期为预售,预计上市日期为 " },
            { kind: "ref", refId: "ref-s3-launch-ai" },
            { kind: "text", text: "。" },
          ],
        },
        { kind: "h2", text: "二、关键参数" },
        {
          kind: "paragraph",
          id: "p-params",
          inlines: [
            { kind: "text", text: "核心参数包含续航 " },
            { kind: "ref", refId: "ref-s3-battery-para" },
            { kind: "text", text: " 个月、防护等级 " },
            { kind: "ref", refId: "ref-s3-rating-para" },
            { kind: "text", text: ",用于指导销售与渠道物料。" },
          ],
        },
        {
          kind: "dataTable",
          id: "table-spec",
          title: "数据表格",
          sourceLabel: "产品规格库",
          rows: [
            { label: "型号", refId: "ref-s3-sku-table" },
            { label: "建议零售价", refId: "ref-s3-price-spec" },
            { label: "电池续航", refId: "ref-s3-battery-table" },
            { label: "防护等级", refId: "ref-s3-rating-table" },
          ],
        },
        { kind: "h2", text: "三、续航与可靠性" },
        {
          kind: "paragraph",
          id: "p-reliability",
          inlines: [
            { kind: "text", text: "可靠性章节复核 " },
            { kind: "ref", refId: "ref-s3-name-position" },
            { kind: "text", text: " 的防护认证 " },
            { kind: "ref", refId: "ref-s3-rating-table" },
            { kind: "text", text: " 与续航数据 " },
            { kind: "ref", refId: "ref-s3-battery-table" },
            { kind: "text", text: "。" },
          ],
        },
        {
          kind: "paragraph",
          id: "p-dangling",
          inlines: [
            { kind: "text", text: "待重绑的上市权益字段:" },
            { kind: "ref", refId: "ref-weekly-presale-gift-dangling" },
          ],
        },
      ],
    },
    {
      exprId: "exp-build-z890-doc",
      docNo: "BUILD-Z890-001",
      template: "装机配置单 V1",
      binding: { objectId: "hw-cpu-ultra7-265k" },
      authorLine: "王芸 · 供应链 | 槽位数据来自装机方案 V1",
      blocks: [
        {
          kind: "meta",
          items: [
            "BUILD-Z890-001",
            "模板:装机方案 V1",
            "绑定:装机方案·Z890 高配",
          ],
        },
        { kind: "h1", text: "装机配置单·Z890" },
        {
          kind: "paragraph",
          id: "p-build",
          inlines: [
            {
              kind: "text",
              text: "配置单由模板槽位实时生成，价格随硬件产品库更新。",
            },
          ],
        },
      ],
    },
  ],
  fieldRefs: [
    {
      id: "ref-s3-price-spec",
      objectId: "prod-s3",
      fieldCode: "price",
      exprId: "exp-spec-doc",
      label: "规格书售价",
      state: "fresh",
    },
    {
      id: "ref-s3-name-title",
      objectId: "prod-s3",
      fieldCode: "name",
      exprId: "exp-spec-doc",
      label: "标题产品名",
      state: "fresh",
    },
    {
      id: "ref-s3-name-position",
      objectId: "prod-s3",
      fieldCode: "name",
      exprId: "exp-spec-doc",
      label: "定位产品名",
      state: "fresh",
    },
    {
      id: "ref-s3-sku-hero",
      objectId: "prod-s3",
      fieldCode: "sku",
      exprId: "exp-spec-doc",
      label: "正文型号",
      state: "fresh",
    },
    {
      id: "ref-s3-sku-table",
      objectId: "prod-s3",
      fieldCode: "sku",
      exprId: "exp-spec-doc",
      label: "表格型号",
      state: "fresh",
    },
    {
      id: "ref-s3-battery-para",
      objectId: "prod-s3",
      fieldCode: "battery_months",
      exprId: "exp-spec-doc",
      label: "正文续航",
      state: "fresh",
    },
    {
      id: "ref-s3-battery-table",
      objectId: "prod-s3",
      fieldCode: "battery_months",
      exprId: "exp-spec-doc",
      label: "表格续航",
      state: "fresh",
    },
    {
      id: "ref-s3-rating-para",
      objectId: "prod-s3",
      fieldCode: "rating",
      exprId: "exp-spec-doc",
      label: "正文防护等级",
      state: "fresh",
    },
    {
      id: "ref-s3-rating-table",
      objectId: "prod-s3",
      fieldCode: "rating",
      exprId: "exp-spec-doc",
      label: "表格防护等级",
      state: "fresh",
    },
    {
      id: "ref-s3-price-agreement",
      objectId: "prod-s3",
      fieldCode: "price",
      exprId: "exp-agreement",
      label: "供货协议售价",
      state: "fresh",
    },
    {
      id: "ref-s3-price-weekly",
      objectId: "prod-s3",
      fieldCode: "price",
      exprId: "exp-weekly",
      label: "周报售价",
      state: "fresh",
    },
    {
      id: "ref-build-cpu-price",
      objectId: "hw-cpu-ultra7-265k",
      fieldCode: "price",
      exprId: "exp-build-z890-doc",
      label: "CPU 价格",
      state: "fresh",
    },
    {
      id: "ref-build-mainboard-name",
      objectId: "hw-mb-prime-z890-p",
      fieldCode: "name",
      exprId: "exp-build-z890-doc",
      label: "主板名称",
      state: "fresh",
    },
    {
      id: "ref-build-mainboard-price",
      objectId: "hw-mb-prime-z890-p",
      fieldCode: "price",
      exprId: "exp-build-z890-doc",
      label: "主板价格",
      state: "fresh",
    },
    {
      id: "ref-s3-launch-ai",
      objectId: "prod-s3",
      fieldCode: "launch_date",
      exprId: "exp-spec-doc",
      label: "上市日期",
      state: "lowConfidence",
      confidence: 0.74,
    },
    {
      id: "ref-weekly-presale-gift-dangling",
      objectId: "prod-s3",
      fieldCode: "presale_gift",
      exprId: "exp-weekly",
      label: "预售权益",
      state: "dangling",
    },
  ],
  kpis: [
    {
      id: "kpi-gmv",
      label: "本月 GMV",
      value: "¥2.4M",
      delta: "+12.4%",
      deltaSign: "up",
      sourceLabel: "渠道销量表",
      visible: true,
    },
    {
      id: "kpi-s3-orders",
      label: "S3 预售订单",
      value: "8,214",
      delta: "+38.2%",
      deltaSign: "up",
      sourceLabel: "产品规格库",
      visible: true,
    },
    {
      id: "kpi-aov",
      label: "平均客单价",
      value: "¥876",
      delta: "-2.1%",
      deltaSign: "down",
      sourceLabel: "合同台账",
      visible: true,
    },
    {
      id: "kpi-active-channels",
      label: "活跃渠道数",
      value: "42",
      delta: "+3",
      deltaSign: "up",
      sourceLabel: "渠道销量表",
      aiAdded: true,
      visible: true,
    },
    {
      id: "kpi-ana-aov-net",
      label: "客单价 Δ(净)",
      value: "-2.1%",
      delta: "近 30 天",
      deltaSign: "down",
      sourceLabel: "分析",
      aiAdded: true,
      visible: false,
    },
    {
      id: "kpi-ana-host",
      label: "主机口径",
      value: "+3.1%",
      delta: "子看板",
      deltaSign: "up",
      sourceLabel: "分析",
      aiAdded: true,
      visible: false,
    },
    {
      id: "kpi-ana-accessory",
      label: "配件口径",
      value: "-5.3%",
      delta: "子看板",
      deltaSign: "down",
      sourceLabel: "分析",
      aiAdded: true,
      visible: false,
    },
  ],
  biBars: [
    { label: "线上直营", value: 6420, percent: 100, tone: "high" },
    { label: "京东", value: 4180, percent: 65, tone: "mid" },
    { label: "天猫", value: 3960, percent: 62, tone: "mid" },
    { label: "线下经销", value: 2850, percent: 44, tone: "low" },
    { label: "运营商", value: 1240, percent: 19, tone: "low" },
  ],
  anaReports: [
    {
      id: "ana-aov-july",
      viewId: "view-dashboard-ana",
      scopeLabel: "近 30 天 · 全部渠道",
      question: "为什么 7 月平均客单价下降 2.1%?",
      sourcesLabel: "渠道销量表 + 产品规格库",
      factorTitle: "贡献度拆解",
      factorMetricLabel: "客单价 Δ · 按因素",
      factors: [
        {
          label: "配件占比下降",
          deltaText: "-3.4%",
          widthPct: 88,
          tone: "change",
        },
        {
          label: "S3 报价同步",
          deltaText: "-1.2%",
          widthPct: 42,
          tone: "change-soft",
        },
        {
          label: "主机单价上移",
          deltaText: "+2.5%",
          widthPct: 64,
          tone: "primary",
        },
        {
          label: "合计净变化",
          deltaText: "-2.1%",
          widthPct: 56,
          tone: "ink",
        },
      ],
      drillTitle: "下钻 · 渠道变动 Top",
      drillTraceLabel: "记录级可追溯",
      drillColumns: [
        { key: "channel", label: "渠道" },
        { key: "delta", label: "客单价 Δ" },
        { key: "share", label: "配件占比" },
      ],
      drillRows: [
        { channel: "线上直营", delta: "-5.2%", share: "31%" },
        { channel: "京东", delta: "-1.8%", share: "24%" },
        { channel: "线下经销", delta: "+0.9%", share: "12%" },
      ],
      insights: [
        {
          title: "主因",
          segments: [
            { text: "配件包客单价由 " },
            { text: "¥210", mono: true },
            { text: " 下探,抵消了主机口径 " },
            { text: "+3.1%", mono: true },
            { text: " 的抬升。" },
          ],
        },
        {
          title: "佐证",
          segments: [
            { text: "S3 权威售价从 " },
            { text: "¥1,299 → ¥1,199", mono: true },
            { text: ",同步后拉低 7 月均值。" },
          ],
        },
      ],
      pinKpiId: "kpi-ana-aov-net",
      childKpiIds: ["kpi-ana-host", "kpi-ana-accessory"],
      childActionLabel: "生成子看板:主机 / 配件口径",
    },
  ],
  rawImport: {
    text: rawImportText,
    spans: [
      rawSpan("华东经销", "primary"),
      rawSpan("门锁 S3", "primary"),
      rawSpan("1199", "change"),
      rawSpan("138****8000", "primary"),
      rawSpan("8 月 18 日", "change"),
      rawSpan("IP65", "primary"),
    ],
    semanticChips: [
      { label: "意图:报价导入", confidence: 0.95 },
      { label: "主体:智能门锁 S3", confidence: 0.92 },
      { label: "来源:供应商邮件", confidence: 0.88 },
    ],
    recent: [
      { id: "import-quote-mail", title: "供应商报价邮件", at: at.import },
      {
        id: "import-channel-cache",
        title: "渠道销量缓存表",
        at: at.validation,
      },
    ],
  },
  chatMessages: [
    {
      id: "chat-seed-ai",
      role: "ai",
      text: "可以让我改数据或改看板,所有 AI 写入都会生成可撤销的变更卡。",
    },
  ],
  reviewRecords: [],
  slotBindings: [
    {
      id: "binding-z890-cpu",
      templateId: "tpl-install-v1",
      exprId: "exp-build-z890",
      slotId: "slot-cpu",
      objectId: "hw-cpu-ultra7-265k",
      updatedBy: "lixiao",
      updatedAt: at.validation,
    },
    {
      id: "binding-z890-psu",
      templateId: "tpl-install-v1",
      exprId: "exp-build-z890",
      slotId: "slot-psu",
      objectId: "hw-psu-850-gold",
      updatedBy: "lixiao",
      updatedAt: at.validation,
    },
    {
      id: "binding-z890-mainboard",
      templateId: "tpl-install-v1",
      exprId: "exp-build-z890",
      slotId: "slot-mainboard",
      objectId: null,
      updatedBy: "lixiao",
      updatedAt: at.validation,
    },
    {
      id: "binding-z890-memory",
      templateId: "tpl-install-v1",
      exprId: "exp-build-z890",
      slotId: "slot-memory",
      objectId: null,
      updatedBy: "lixiao",
      updatedAt: at.validation,
    },
    {
      id: "binding-z890-gpu",
      templateId: "tpl-install-v1",
      exprId: "exp-build-z890",
      slotId: "slot-gpu",
      objectId: null,
      updatedBy: "lixiao",
      updatedAt: at.validation,
    },
    {
      id: "binding-b860-cpu",
      templateId: "tpl-install-v1",
      exprId: "exp-build-b860",
      slotId: "slot-cpu",
      objectId: "hw-cpu-ultra7-265k",
      updatedBy: "lixiao",
      updatedAt: at.validation,
    },
    {
      id: "binding-b860-psu",
      templateId: "tpl-install-v1",
      exprId: "exp-build-b860",
      slotId: "slot-psu",
      objectId: "hw-psu-850-gold",
      updatedBy: "lixiao",
      updatedAt: at.validation,
    },
    {
      id: "binding-b860-mainboard",
      templateId: "tpl-install-v1",
      exprId: "exp-build-b860",
      slotId: "slot-mainboard",
      objectId: "hw-mb-prime-b860m-a",
      updatedBy: "lixiao",
      updatedAt: at.validation,
    },
    {
      id: "binding-b860-memory",
      templateId: "tpl-install-v1",
      exprId: "exp-build-b860",
      slotId: "slot-memory",
      objectId: null,
      updatedBy: "lixiao",
      updatedAt: at.validation,
    },
    {
      id: "binding-b860-gpu",
      templateId: "tpl-install-v1",
      exprId: "exp-build-b860",
      slotId: "slot-gpu",
      objectId: null,
      updatedBy: "lixiao",
      updatedAt: at.validation,
    },
  ],
  changeSets: [
    {
      id: "changeset-ai-quote",
      source: "ai",
      status: "pending",
      title: "供应商报价邮件解析",
      actor: "ai",
      createdAt: at.import,
      items: [
        {
          id: "ai-price",
          op: "updateField",
          target: {
            entityType: "field",
            entityId: "prod-s3",
            fieldCode: "price",
          },
          oldValue: 1299,
          nextValue: 1199,
          confidence: 0.96,
          confirmed: true,
          applied: true,
        },
        {
          id: "ai-battery",
          op: "updateField",
          target: {
            entityType: "field",
            entityId: "prod-s3",
            fieldCode: "battery_months",
          },
          oldValue: 12,
          nextValue: 14,
          confidence: 0.92,
          confirmed: true,
          applied: true,
        },
        {
          id: "ai-rating-skip",
          op: "updateField",
          target: {
            entityType: "field",
            entityId: "prod-s3",
            fieldCode: "rating",
          },
          oldValue: "IP65",
          nextValue: "IP65",
          confidence: 0.98,
          confirmed: true,
          applied: true,
        },
        {
          id: "ai-contract",
          op: "createObject",
          target: {
            entityType: "object",
            entityId: "contract-east-s3",
          },
          objectTypeCode: "contracts",
          fields: {
            name: "华东智联 · S3 报价",
            product: "门锁 S3",
            channel: "华东经销",
            quote: 1199,
            contact: "老李 138****8000",
            amount: 880000,
          },
          confidence: 0.89,
          confirmed: true,
          applied: true,
        },
        {
          id: "ai-launch",
          op: "updateField",
          target: {
            entityType: "field",
            entityId: "prod-s3",
            fieldCode: "launch_date",
          },
          oldValue: null,
          nextValue: "2026-08-18",
          confidence: 0.74,
          needsConfirm: true,
          confirmed: false,
        },
      ],
    },
    {
      id: "changeset-manual-channel",
      source: "manual",
      status: "pending",
      title: "陈默调整线下经销销量",
      actor: "chenmo",
      createdAt: at.validation,
      items: [
        {
          id: "manual-sales",
          op: "updateField",
          target: {
            entityType: "field",
            entityId: "sales-offline-dealer",
            fieldCode: "month_sales",
          },
          oldValue: 2850,
          nextValue: 2910,
          confidence: 1,
          confirmed: true,
        },
      ],
    },
  ],
  changeEvents: [
    {
      id: "us-canvas-history-003",
      track: "view",
      actor: "chenmo",
      target: { entityType: "object", entityId: "view-portal-canvas" },
      old: "三节点散布",
      next: "等宽对齐",
      syncedRefs: 0,
      at: "2026-07-09T17:20:00+08:00",
      inverse: null,
      inverseView: null,
    },
    {
      id: "us-canvas-history-002",
      track: "view",
      actor: "lixiao",
      target: { entityType: "object", entityId: "view-portal-canvas" },
      old: "无 G2",
      next: "添加节点 G2 并连线",
      syncedRefs: 0,
      at: "2026-07-08T14:10:00+08:00",
      inverse: null,
      inverseView: null,
    },
    {
      id: "us-canvas-history-001",
      track: "view",
      actor: "zhouran",
      target: { entityType: "object", entityId: "view-portal-canvas" },
      old: "显示电池续航",
      next: "隐藏字段 电池续航",
      syncedRefs: 0,
      at: "2026-07-04T16:40:00+08:00",
      inverse: null,
      inverseView: null,
    },
  ],
  activity: [
    {
      id: "act-1",
      actor: "ai",
      summary: "续航 12→14 + 看板加卡",
      tracks: ["data", "view"],
      at: at.confirmed,
    },
    {
      id: "act-2",
      actor: "wangyun",
      summary: "确认写入 ¥1,199,同步 3 篇文档",
      tracks: ["data"],
      at: at.confirmed,
    },
    {
      id: "act-3",
      actor: "ai",
      summary: "解析报价邮件:改 2 / 增 1 / 待确认 1",
      tracks: ["data"],
      at: at.import,
    },
    {
      id: "act-4",
      actor: "lixiao",
      summary: "补充 S3 与 G2 互联协议批注",
      tracks: ["view"],
      at: at.confirmed,
    },
    {
      id: "act-5",
      actor: "chenmo",
      summary: "提交线下经销销量调整审批",
      tracks: ["data"],
      at: at.validation,
    },
  ],
  outputSnapshots: [
    {
      id: "snapshot-s3-spec-1024",
      scope: "exp-spec-doc",
      createdAt: at.confirmed,
      payload: {
        title: "S3 规格书",
        summary: "已输出含 ¥1,199 售价与 14 个月续航的规格书。",
      },
    },
  ],
  plugins: [
    {
      id: "plug-3d-assembly",
      name: "三维架构图",
      version: "2.3",
      vendor: "同源官方",
      industry: "制造业",
      tagline: "把部件层级、尺寸与材质描述为可交付的三维装配视图。",
      formsProvided: [
        {
          code: "assembly",
          name: "三维装配视图",
          desc: "按部件层级生成装配关系与结构总览。",
        },
        {
          code: "exploded",
          name: "爆炸图",
          desc: "把组件拆解为层级清晰的爆炸视图。",
        },
      ],
      contract: {
        reads: ["部件层级 · 树", "尺寸 · 数值", "材质 · 文本"],
        writes: ["装配关系"],
        writeNote: "与表格 / 文档同步",
      },
      scope: "all",
      scopeGroupLabel: "产品中心",
      installed: true,
      enabled: true,
      updateTo: "2.4",
      usedByExprIds: ["exp-portal"],
    },
    {
      id: "plug-gantt-plus",
      name: "工程甘特 Gantt+",
      version: "1.8",
      vendor: "筑云科技",
      industry: "建筑工程",
      tagline: "用工程阶段、里程碑和资源表讲清楚项目计划。",
      formsProvided: [
        {
          code: "gantt",
          name: "工程甘特",
          desc: "把阶段日期渲染为可审阅的甘特计划。",
        },
        {
          code: "milestone",
          name: "里程碑泳道",
          desc: "突出关键交付点与责任团队。",
        },
        {
          code: "resource",
          name: "资源负荷图",
          desc: "按人员与工种汇总资源占用。",
        },
      ],
      contract: {
        reads: ["阶段 · 日期", "责任人 · 人员", "工期 · 数值"],
        writes: ["阶段排期"],
        writeNote: "写回项目计划字段",
      },
      scope: "all",
      scopeGroupLabel: "产品中心",
      installed: true,
      enabled: true,
      usedByExprIds: ["exp-build-z890"],
    },
    {
      id: "plug-finsuite",
      name: "财务三表 FinSuite",
      version: "3.1",
      vendor: "数衡",
      industry: "金融",
      tagline: "把收入、成本与现金流组织成财务三表口径。",
      formsProvided: [
        {
          code: "income",
          name: "利润表",
          desc: "按期间汇总收入、成本与毛利。",
        },
        {
          code: "cashflow",
          name: "现金流量表",
          desc: "把经营、投资、筹资现金流分组展示。",
        },
        {
          code: "balance",
          name: "资产负债表",
          desc: "按资产、负债与权益生成静态表。",
        },
      ],
      contract: {
        reads: ["金额 · 数值", "期间 · 日期", "科目 · 文本"],
        writes: ["财务口径"],
        writeNote: "写回财务分类字段",
      },
      scope: "all",
      scopeGroupLabel: "产品中心",
      installed: false,
      enabled: false,
      usedByExprIds: [],
    },
    {
      id: "plug-medform",
      name: "病历结构化 MedForm",
      version: "1.2",
      vendor: "康码",
      industry: "医疗健康",
      tagline: "把病历文本拆成诊断、医嘱与随访表单。",
      formsProvided: [
        {
          code: "record",
          name: "结构化病历",
          desc: "按病程、诊断和医嘱组织病历字段。",
        },
        {
          code: "followup",
          name: "随访问卷",
          desc: "把复诊记录整理为连续随访问卷。",
        },
      ],
      contract: {
        reads: ["诊断 · 文本", "医嘱 · 文本", "时间 · 日期"],
        writes: ["病历段落"],
        writeNote: "写回病历结构字段",
      },
      scope: "all",
      scopeGroupLabel: "产品中心",
      installed: false,
      enabled: false,
      usedByExprIds: [],
    },
    {
      id: "plug-lexgrid",
      name: "条款对照 LexGrid",
      version: "2.0",
      vendor: "律衡",
      industry: "法务合规",
      tagline: "把合同条款、风险等级和修改建议对齐到网格。",
      formsProvided: [
        {
          code: "clause-grid",
          name: "条款对照表",
          desc: "横向对比合同条款与标准条款。",
        },
        {
          code: "risk-ledger",
          name: "风险台账",
          desc: "按风险等级整理条款差异与处理建议。",
        },
      ],
      contract: {
        reads: ["条款 · 文本", "风险等级 · 枚举", "责任方 · 文本"],
        writes: ["条款标注"],
        writeNote: "写回合同审查字段",
      },
      scope: "all",
      scopeGroupLabel: "产品中心",
      installed: true,
      enabled: true,
      usedByExprIds: ["exp-spec-doc"],
    },
    {
      id: "plug-bim-view",
      name: "BIM 模型视图",
      version: "0.9",
      vendor: "筑云科技",
      industry: "建筑工程",
      tagline: "把构件清单与空间关系展示为 BIM 模型视图。",
      formsProvided: [
        {
          code: "model",
          name: "BIM 模型视图",
          desc: "按构件和楼层生成模型浏览视图。",
        },
      ],
      contract: {
        reads: ["构件 · 树", "楼层 · 文本", "坐标 · 数值"],
        writes: [],
        writeNote: "当前 Beta 仅读取数据",
      },
      scope: "all",
      scopeGroupLabel: "产品中心",
      installed: false,
      enabled: false,
      beta: true,
      usedByExprIds: [],
    },
  ],
  simScenarios: [
    {
      id: "sim-visitor",
      name: "访客到访 · 指纹开锁",
      duration: 10,
      events: [
        {
          id: "sim-event-fingerprint",
          nodeObjectId: "prod-s3",
          label: "指纹开锁",
          kind: "source",
        },
        {
          id: "sim-event-gateway",
          nodeObjectId: "prod-g2",
          viaRelationId: "rel-s3-g2-interconnect",
          label: "收到事件",
          kind: "relay",
        },
        {
          id: "sim-event-push",
          nodeObjectId: "prod-d2-pro",
          viaRelationId: "rel-d2pro-g2-interconnect",
          label: "推送弹窗",
          kind: "action",
          check: true,
        },
        {
          id: "sim-event-recording",
          nodeObjectId: "prod-e1",
          viaRelationId: "rel-e1-g2-interconnect",
          label: "联动录像",
          kind: "action",
        },
      ],
    },
  ],
};

export function cloneDemoSeed(): DemoSeed {
  return structuredClone(demoSeed) as DemoSeed;
}
